### ISSUE TITLE
Forwardable is extended without requiring it

### ISSUE THREAD

**Issue by ww-daniel-mora** [waterlink/rspec-json_expectations#32]
When using this gem. You get the following error if no one required forwardable first.
```
Failure/Error: require 'rspec/json_expectations'

NameError:
  uninitialized constant RSpec::JsonExpectations::Matchers::UnorderedArrayMatcher::Forwardable
# ./spec/utils/add_office_spec.rb:4:in '<top (required)>'
# ------------------
# --- Caused by: ---
# LoadError:
#   cannot load such file -- rspec/json_expectations
#   ./spec/utils/add_office_spec.rb:4:in '<top (required)>'
```

**Comment by waterlink** [comment]
This is done. Thank you @ww-daniel-mora !
